# Generated by Django 2.1.3 on 2018-11-23 11:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('follower', djongo.models.fields.ListField(default=[1, 2])),
                ('following', djongo.models.fields.ListField(default=[1, 2])),
            ],
        ),
    ]
